# База Данных | Важная вещь, без нее плагин работать - не будет.
# Данные - берутся именно с Вашего сервера с Вашей СУБД.
Database:
  type: "PostgreSQL"        # PostgreSQL, MySQL, MariaDB
  user: "postgre"           # Пример: E1m0
  pass: "postgre"           # Пример: Elm0Dev
  name: "E1m0Admin"         # Пример: Server_Prod
  host: "127.0.0.1"         # Пример: 217.171.146.202
  port: 5433                # Пример: 3306, 5432, 5433

# Параметры плагина | Параметры самого плагина на которые он будет опираться в работе своих функций.
Settings:
  consoleLogActive: true      # Сообщения | Будут ли логироватся действия администратора?
  prefixEnable: false         # Сообщения | Будет ли показыватся префикс? Пример: E1m0-Admin - Внимание | У Вас - нет на это права!
  prefix: "&cE1m0-Admin |"    # Сообщения | Префикс при системных сообщениях. Пример: ADM | У вас нет на это прав!
  world: "world"              # Мир       | В папке с Вашим сервером, у Вас есть в server.properties название Вашего мира.

  Dev:
    rewatchTick: 5 # Слежка |❗ Опасная настройка, только для знающих людей с уровнем допуска DEV Рекомендуемое значение: 10+.
    # ❓- Сколько тиков будет длиться один кадр слежки? Меньше тиков = больше плавности == БОЛЬШЕ нагрузка на сервер! Если у Вас тпс ниже 20 - Не советую.
    rewatchVectorX: 3 # Слежка | На сколько "отдаленно" будет камера у администратора?
    rewatchVectorY: 3 # Слежка | На сколько высоко будет камера у администратора?
    rewatchVectorZ: 3 # Слежка | На сколько "глубоко" будет камера у администратора?

    salaryCheck: 60 # | ❗ Через сколько минут будет проходить проверка scheduler на зарплаты админов? Советую не трогать если не знаем что такое. Действия с базой там плотные.

# Параметры | Связанные с разрешениями для главных администраторов серверов+,
#  которые в праве сами выбирать способности своей администрации.
Server:
  # - | ADMIN
  invisibility: true # Невидимость | Включать ли возможность e1m0-невидимки?
  rewatch: true # Слежка за юзером | Включать ли возможность e1m0-rewatcher?
  report: true # Репорты | Включить ли возможность отправлять и управлять репортами?

  # - | PLAYER
  reportPlayer: true # Слежка за юзером | Включать ли возможность e1m0-rewatcher?

  # - | STAFF
  abonusall: true # Бонусы | Включить ли возможность выдавать бонусы всем?
  abonus: true # Бонусы | Включить ли возможность выдавать бонус админу?

  adminPay: true # Зарплата | Каждый отыгранный администратором час = определенные действия в отношении администратора.
  adminBonus: true # Зарплата | Каждый дополнительный наигранный час = дополнительные действия.

  emergencyRep: true # Репорт | Будет ли оповещение в чате администрации при: Срочном репорте?
  donateReport: true # Репорт | Будет ли оповещение в чате администрации при: Донат репорте?
  newReport: true    # Репорт | Будет ли оповещение в чате администрации при: Новом репорте?

  # PermissionManager:
  # При каких разрешениях у администраторов будут работать команды?
  # Вы - можете полностью настроить какие команды включены на сервере, какие выключены, у кого есть к ним доступ у кого нет. Полная адаптивность к Вашему серверу.
Permissions:
  # 🎫 | Главные разрешения | Печать администратора.
  admin: "e1admin.admin"                     # Печать | Является-ли данный пользователь администратором сервера?
  staff: "e1admin.staff"                   # Печать | Является-ли данный администратор, главой сервера?

  # 🎫 | Например разрешение обычных администраторов:
  invisibility: "e1admin.invise"           # Невидимость | Какое разрешение на просмотр и использование способности
  rewatch: "e1admin.rewatch"               # Слежка | Какое разрешение на просмотр и использование способности?
  arep: "e1admin.arep"                     # Репорт | Какое разрешение на просмотр и использование способности?

  # 🔐 | Например кураторы:
  adminbonus: "e1admin.adminbonus"         # Администрация | Какое разрешение у администратора для выдачи бонуса другому администраторУ?
  adminbonusall: "e1admin.adminbonusall"   # Администрация | Какое разрешение у администратора для выдачи бонуса другим администраторАМ?

  # ❗ | STAFF:
  secretcode: "e1admin.asecret"            # Админ | Какое разрешение у высших адм на установление секретного пароля?
  downadm: "e1admin.downadmin"             # Админ | Какое разрешение у высших адм на понижение других администраторов?
  deladm: "e1admin.deladmin"               # Админ | Какое разрешение у высших адм на удаление других администраторов?
  setadm: "e1admin.setadmin"               # Админ | Какое разрешение у высших адм на постановление других администраторов?
  upadm: "e1admin.upadmin"                 # Админ | Какое разрешение у высших адм на повышение других администраторов?

# Параметры | Связанные с игрой администраторации, их зарплаты, АЗ, их бонусы за безумные трюки,
#  которые Вы можете полностью настраивать как душе угодно, развлекайтесь.
Admin:
  # Амин-Зона | Сюда, администраторы попадают при регистрации например, или при окончании реватча (/reoff)
  # Амин-Зона | ❗ Лучше сразу заполнить.
  AdminZone:
    world: "world"
    x: 777
    y: 777
    z: 777

  #TODO: ПРОВЕРИТЬ
  Salary:
    # Или же - AdminPay, зарплата для администраторов которая выдается за определенные действия в игре.
    # Можно так же настроить действия для большего кол-ва часов выставляя hour.
    SalaryActions:
      1:
        hour: 1
        Actions:
          - "msg %player Привет. Ты отыграл час! Твоя зарплата: %salary!"
      2:
        hour: 2
        Actions:
          - "msg %player hello1 %salary, ты отыграл уже %loop час(а) или же целых два часа. Вот твоя награда!"
          - "eco give %player 100"

  # Параметры бонусов | Старшая администрация может выдать бонус в N кол-ве, Вам решать что это будет, например у кого-либо есть админ коины, вставляете команду сюда и Воуаля.
  # Крутить %admin %bonus можно в любом порядке, это переменные абстракции которые перенимают форму заданную плагином.
  Bonus:
    giveBonus: "eco give %admin %bonus" # ❗НУЖЕН VAULT, лучше заменить на что то другое, это - Ваша фантазия уже.

  # | Staff
  # Вот тут - очень интересно. Полностью настраиваемая система рангов, вы можете создавать сколько угодно уровней
  #  админ-допуска, называть их по-разному, не советую конечно менять названия в runtime потому что может быть путаница,
  #  но тут - и лежат Ваши администраторы и их разрешения.
  AdminRanks:
    # Минимальный ранг на который будет поставлен администратор при setAdmin.
    mladm:
      prefix: "Младший администратор"   # Важно | Какой префикс в DB будет выдаваться при постановлении на адм?
      weight: 1                         # Важно | Какой вес будет у данной роли? Например: Некоторые администраторы - не могут забанить некоторых игроков.
      salary: 333                       # Важно | Какая зарплата будет у администратора в Вашей валюте?
      scom: "eco give %player %salary"  # Важно | Какая команда будет выдавать валюту которая закреплена за администратором? Или например предмет из ресурс-пака?

    # Около средние ранги на который будет поставлен администратор при повышении.
    adm:
      prefix: "Администратор"
      salary: 777
      weight: 2
      scom: "eco give %player %salary"

    # Здесь например ваши максимальные ранги среди всех.
    stadm:
      prefix: "Ст. Администратор"
      weight: 3
      salary: 888
      scom: "eco give %player %salary"

  # PIN-Code | Или же SecretCode, параметры при котором используются действия с PIN кодом администратора.
  # Каждому администратору Выдается старшим администратором свой PIN-Code и позже вводится на постоянной основе.
  SecretCode:
    wrongCodeTrigger: true  # ❗| Будет ли извещение, что администратор не правильно ввел пароль?
    accessCodeTrigger: true # ❗| Будет ли извещение, что администратор правильно ввел пароль?

    adminAccessNotify: "&aПоприветствуйте! Администратор %admin зарегистрировался в системе!" # | Успешная регистрация в системе.
    wrongCodeNotify: "&4&bОй! Администратор %admin ввел не правильный секретный код!"         # | Не успешная регистрация в системе.


    # Trigger Action | Действия при одном из состояний входа, то есть, если админ не правильно ввел пин код, я могу забанить его аккаунт,
    # Отобрать права, или просто кикнуть. А если ввел правильно, могу написать в админ чат или весь чат, что все хорошо.
    Actions:
      accessCodeActions:
        - "say §aАдминистратор %admin успешно авторизовался!"
      wrongCodeActions:
        - "kick %admin Не верно ввел админ код!"

  # Репортики | Связанные с игрой администрации и игроков, контрольные слова, статусы, бонусы и прочее.
  #  Здесь можно настроить GUI, авто-ответы на репорты, бонусы за репорты и т.д:
  Report:
    minReportLength: 3 # Репорт | Минимальное кол-во символов в репорте для администрации?
    reportMaxSize: 44 # Репорт | Сколько будет максимальное кол-во репортов до переполнения?

    # Репортики | Статусы, которые приобретают свою роль в базе и GUI.
    status_send: "&aОтправлен!"
    status_inJob: "&6В работе.."
    status_answered: "&cОтвечен."

    # Репортики | Слова, которые в репорте вызывают триггер emergencyRep, на который можно быстро отреагировать просто нажав на сообщение
    EmergencyReportSword:
      - "убивают"
      - "гриферят"
      - "читерят"

    # | https://minecraftsounds.com/
    # Репортики | Новый репорт, действия + звук для всей администрации?
    NewReport:
      sound: "entity.player.attack.knockback"
      reportMessage:
        - ""
        - "&7Внимание, поступил новый &cрепорт&7: &b%content&7. Отправитель: %player"
        - ""

    # | https://minecraftsounds.com/
        # Репортики | Срочный репорт, действия + звук для всей администрации?
    EmergencyReport:
      sound: "entity.player.levelup"
      emergencyMessage:
        - ""
        - "&4Внимание 🚨 &7| Обнаружен срочный репорт: &7%content"
        - ""

    # | https://minecraftsounds.com/
    # Репортики | Донат репорт, действия + звук для всей администрации?
    DonateReport:
      sound: "entity.ender_dragon.hurt"
      permission: "e1admin_bypass"
      donateMessage:
        - ""
        - "<gradient:#FD1AB6:#6554B6>Внимание❗ Репорт от VIP клиента! %content. Отправитель: %player</gradient>"
        - ""

    # Репортики | Функция при которой при нажатии на срочный репорт не нужно вводить форму для определенного администратора.
    # При /arep - Нужно указывать форму сервера на некоторых проектах. Пример: /arep Слежу за Вами.. // By E1m0
    # Здесь же - Форма автоматическая.
    AutoReport:
      enable: true
      auto_Answer: "&cРепорт | Спешим к Вам на помощь!"

    # Репортики | Если навести на emergency report что будет показано?
    HoverReport:
      - "Нажмите чтобы взять ❤️"
      - "&cРепорт&7: %content"
      - "&aСтатус&7: %status"
      - "&4Принял&7: %admin"
      - ""
      - "&aОтправил&7: %player"
      - "&7Дата: %date"

    # | https://minecraft-inside.ru/blocks/
    # Репортики | Ну тут думаю понятно, адаптивное меню если что-то не нравится.
    GUI:
      ReportGUI:
        NAME: "&cМеню репортов"
        SIZE: 54

        items:
          close:
            slot: 49
            name: "&cЗакрыть."
            item: "BARRIER"
            lore:
              - "Нажмите чтобы закрыть."

      # Репортики | Какой item в меню у ReportGUI? Он отдельно, потому что это не статический обьект + не постоянная форма, если объяснять разработчику: Я не могу отдавать в статику не стабильный Mutable state.
      ReportItem:
        NAME: "%content"
        ITEM: PLAYER_HEAD
        LORE: # Форма как будет выглядеть репорт при наведении | Или же - его лор.
          - "&7Репорт: %content"
          - "&7Статус: %status"
          - ""
          - "&7Отправил: %player"
          - "&7Дата: %date"

# Мои дорогие сообщения, Вы - можете их разветвлять как в примере с несколькими сообщениями например как: teleportToAZ.
# Так же - Вы можете полностью менять их структуру и выделять сообщения не одним пробелом а больше, здесь - Ваше место фантазии.
Messages:
  teleportToAZ:
    - "&aУспех! &7| &aУспешная операция"
    - "&7Вы &aуспешно &7были телепортированы в &aадмин-зону&7!"
    - "&aУспех! &7| &aУспешная операция"

  inviseOn: "&6Вы включили невидимку!"
  inviseOff: "&7Вы отключили невидимку!"

  secretCodeAccess: "&cВы — успешно авторизовались под своим именем в системе администрации!"

  reportTake: "&aВы успешно взяли репорт игрока&7: %player. Содержимое: %content"
  reportMessagePlayerFast: "&aАдминистратор &6%admin &a— успешно взял ваш репорт в работу!"

  adminBonusAll: "&7Администратор %staff выдал всем бонус: %bonus $!"
  adminBonus: "&7Администратор %staff выдал Вам бонус: %bonus $! Сообщение: %message"
  adminPay: "&7Вы получили админ зарплату в виде: %salary $!"

  successfulSetAdmin: "&cПоздравляем! Вы — были успешно назначены на пост администратора %level уровня, &6администратором %staff"
  successfulSetStaff: "&6%admin &a— был успешно назначены на пост администратора &6%level &aуровня"

  successfulUpStaff: "&aВы успешно повысили администратора &6%admin"
  successfulUpAdmin: "&aВы успешно были повышены администратором &6%staff"

  successfulDownStaff: "Вы успешно понизили администратора &6%admin"
  successfulDownAdmin: "Вы были понижены администратором &6%staff.."

  changeCodeAdmin: "❗ &cВнимание! Вам сменили игровой код администратора! &6Тот кто сменил: %staff. &aНовый код: &6%code. Не потеряйте его!"
  changeCodeStaff: "❗ &cВнимание! Вы сменили игровой код администратора %admin. &6Его новый код: %code!"

  reportSended: "&aРепорт %report был успешно отправлен!"
  reportAdminResponse: "&aВам ответил администратор &6%admin, &aс ответом: &6%response"

  deleteAdminByStaff: "&cВы были сняты администратором &6%staff!"
  successfulDeleteAdmin: "&aВы успешно сняли администратора &6%admin!"

  # CONSOLE ACTIONS
  successfulAdminDelete: "&fЛОГ &7| &aАдминистратор успешно удален!"
  successfulAdminDown: "&fЛОГ &7| &aАдминистратор успешно понижен!"
  successfulAdminSet: "&fЛОГ &7| &aАдминистратор успешно поставлен!"
  successfulAdminUp: "&fЛОГ &7| &aАдминистратор успешно повышен!"

  Errors:
    nullPlayer: "&cТакого игрока не существует..."
    lengthError: "&cНеправильное использование команды!"
    consoleError: "Консоли нельзя.."

    permissionError: "&cУ вас нет доступа к данной команде!"

    secretCodeNotInput: "&6Внимание! &7| &cВы еще не получили права администратора своего уровня, просим Вас подтвердите статус администратора: &a/aaccess!"
    secretCodeIsWrong: "&cВы ввели неправильный код! Попробуйте снова!"

    reportSizeIsMax: "&cИзвините! Все администраторы сейчас перегружены репортами, попробуйте пожалуйста, позже!"
    reportLengthError: "&cМинимальный набор репорта составляет &6%len &cсимволов!"

    # STAFF
    staffPermissionError: "&cУ вас нет печати: &6Старшего администратора!"

    setAdminWeightIsNull: "&cВыдаваемый ранг — должен быть больше 0!"
    setAdminWeightNotFound: "&cВведенный ранг — НЕ найден.."

    downAdminLevelError: "&cАдминистратор уже находится на минимальном уровне!"
    downAdminWeightError: "&cВы — не можете понизить данного администратора!"

    deleteAdminWeightError: "&cВы — не можете уволить данного администратора!"

    upAdminWeightError: "&cВы — не можете повысить данного администратора!"
    upAdminLevelError: "&cАдминистратор уже находится на максимальном уровне!"
    upAdminSelfError: "&cВы не можете повысить себя!"

    secretCodeHasInputted: "&cВы уже вводили секретный пин!"
    setAdminCodeIsWrong: "&cВы не правильно ввели новый код для администратора, &6пример кода: 7777"

    reoffNullError: "&cВы не за кем не следите и не можете отключится!"

    playerHaveReport: "&cУ вас уже есть репорт!"
    noReportsInMemory: "&cДоступных репортов сейчас нет!"
    adminSendReportToAdmins: "&cВы же администратор.. Как можно отправлять репорты &6самому себе?"

    # CONSOLE ACTIONS

    upAdminNotAdminError: "&fЛОГ &7| &cАдминистратора указанного в команде - не существует в базе."

    setAdminIsAdminError: "&fЛОГ &7| &cЧеловек уже есть в базе данных!"
    setAdminWeightError: "&fЛОГ &7| &cАдминистратор НЕ поставлен - Ошибка weight!"

  ConsoleLogs:
    accessLog: "&fЛОГ &7| &7Администратор &6%admin успешно авторизовался в системе ✅."
    inviseLog: "&fЛОГ &7| &7Администратор &6%admin зашел в невидимку 👻.."
    reportLog: "&fЛОГ &7| &7Администратор &6%admin успешно взялся за репорты с формой %response 🧑‍💻"
    rewatchLog: "&fЛОГ &7| &7Администратор &6%admin зашел в слежку за игроком %player 🎥 - 💺🛏️..." # https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfj3K8zuo7Zp77tu-YACPa7PGuxYOasedpEVRPj1WEVpRcKpFKhEzVBVY&s=10
